apiVersion: apps/v1
kind: Deployment
metadata:
  name: openprequal-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: openprequal-backend
  template:
    metadata:
      labels:
        app: openprequal-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: 8001
        env:
        {{- range $key, $value := .Values.backend.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
