apiVersion: apps/v1
kind: Deployment
metadata:
  name: openprequal-server
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: openprequal-server
  template:
    metadata:
      labels:
        app: openprequal-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: 8000
        env:
{{- range $key, $value := .Values.backend.env }}
          - name: {{ $key }}
            value: "{{ $value }}"
{{- end }}
          - name: BACKEND_HOST
            value: openprequal-server
