# File: helm/openprequal/templates/servicemonitor.yaml
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "openprequal.fullname" . }}-monitor
  labels:
    release: {{ .Values.serviceMonitor.release }}
spec:
  selector:
    matchLabels:
      app: {{ include "openprequal.name" . }}
  namespaceSelector:
    matchNames:
      - {{ .Values.serviceMonitor.namespace }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
