# File: k8s/prequal-sidecar-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prequal-sidecar-monitor
  labels:
    release: prometheus-stack  # Adjust to match your Prometheus install
spec:
  selector:
    matchLabels:
      app: prequal-sidecar
  namespaceSelector:
    matchNames:
      - default  # Adjust if deploying to another namespace
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s